# Generated by Django 3.1.3 on 2020-12-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201216_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(help_text='150x150px', upload_to='image/', verbose_name='Ссылка картинки'),
        ),
    ]
