# Generated by Django 3.1.3 on 2021-01-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name model')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('product', models.CharField(blank=True, max_length=250, null=True, verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Форма безкоштовного прорахунку',
            },
        ),
    ]
