# Generated by Django 3.1.3 on 2021-02-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210201_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productwindow',
            options={'verbose_name': 'Окна', 'verbose_name_plural': 'Окна'},
        ),
    ]
